name = "meep"
main = "src/worker.js"
compatibility_date = "2025-08-04"

[site]
bucket = "./dist"

[build.upload]
format = "modules"

[vars]
# Optional vars here

[[bindings]]
type = "site"
name = "ASSETS"

[observability.logs]
enabled = true



