name = "meep"
main = "src/worker.js"
compatibility_date = "2025-08-04"

[site]
bucket = "./dist"

[[kv_namespaces]]
binding = "ASSETS"
id = "db6ad5cc2e06495bbce712c731c7dc66"

[observability.logs]
enabled = true



